import {
  ArrowRightLeft,
  BoxesIcon,
  Building2,
  CircleDollarSign,
  ClipboardList,
  FileImageIcon,
  Footprints,
  LayoutTemplate,
  type LucideProps,
  Mail,
  Menu,
  PackageSearch,
  PanelsTopLeft,
  RssIcon,
  Search,
  SendIcon,
  Settings,
  ShieldUserIcon,
  Star,
  TagIcon,
  Tags,
  TextCursorInput,
  TruckIcon,
  UsersRound,
} from "lucide-react";
import { type CollectionSlug, type GlobalSlug } from "payload";
import { type ExoticComponent } from "react";

export const navIconMap: Partial<Record<CollectionSlug | GlobalSlug, ExoticComponent<LucideProps>>> = {
  redirects: ArrowRightLeft,
  forms: TextCursorInput,
  "form-submissions": SendIcon,
  search: Search,
  administrators: ShieldUserIcon,
  pages: LayoutTemplate,
  posts: RssIcon,
  media: FileImageIcon,
  categories: TagIcon,
  header: Menu,
  footer: Footprints,
  customers: UsersRound,
  orders: ClipboardList,
  fulfilment: Building2,
  products: PackageSearch,
  productCategories: TagIcon,
  productSubCategories: Tags,
  productReviews: Star,
  emailMessages: Mail,
  shopSettings: Settings,
  shopLayout: PanelsTopLeft,
  "inpost-courier-cod": TruckIcon,
  "inpost-courier": TruckIcon,
  "inpost-pickup": BoxesIcon,
  paywalls: CircleDollarSign,
};

export const getNavIcon = (slug: string) =>
  Object.hasOwn(navIconMap, slug) ? navIconMap[slug as CollectionSlug | GlobalSlug] : undefined;
