export const orderDetails = {
  "ORD-001": {
    id: "ORD-001",
    date: "2024-01-20",
    status: "delivered",
    total: "$129.99",
    subtotal: "$119.99",
    shipping: "$10.00",
    tax: "$0.00",
    trackingNumber: "1Z999AA1234567890",
    estimatedDelivery: "2024-01-22",
    actualDelivery: "2024-01-21",
    shippingAddress: {
      name: "John Doe",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zip: "10001",
      country: "United States",
    },
    billingAddress: {
      name: "John Doe",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zip: "10001",
      country: "United States",
    },
    paymentMethod: {
      type: "Visa",
      last4: "4242",
      expiry: "12/25",
    },
    products: [
      {
        id: "1",
        name: "Wireless Headphones",
        quantity: 1,
        price: "$79.99",
        image: "/placeholder.svg?height=80&width=80&text=Headphones",
        sku: "WH-001",
      },
      {
        id: "2",
        name: "Phone Case",
        quantity: 2,
        price: "$25.00",
        image: "/placeholder.svg?height=80&width=80&text=Case",
        sku: "PC-002",
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-01-20 10:30 AM",
        completed: true,
        description: "Your order has been received and is being processed",
      },
      {
        status: "Payment Confirmed",
        date: "2024-01-20 10:35 AM",
        completed: true,
        description: "Payment has been successfully processed",
      },
      {
        status: "Processing",
        date: "2024-01-20 2:00 PM",
        completed: true,
        description: "Your items are being prepared for shipment",
      },
      {
        status: "Shipped",
        date: "2024-01-21 9:00 AM",
        completed: true,
        description: "Your order has been shipped and is on its way",
      },
      {
        status: "Out for Delivery",
        date: "2024-01-21 8:00 AM",
        completed: true,
        description: "Your package is out for delivery",
      },
      {
        status: "Delivered",
        date: "2024-01-21 3:45 PM",
        completed: true,
        description: "Package delivered successfully",
      },
    ],
  },
  "ORD-002": {
    id: "ORD-002",
    date: "2024-01-18",
    status: "shipped",
    total: "$89.99",
    subtotal: "$79.99",
    shipping: "$10.00",
    tax: "$0.00",
    trackingNumber: "1Z999AA1234567891",
    estimatedDelivery: "2024-01-25",
    actualDelivery: null,
    shippingAddress: {
      name: "John Doe",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zip: "10001",
      country: "United States",
    },
    billingAddress: {
      name: "John Doe",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zip: "10001",
      country: "United States",
    },
    paymentMethod: {
      type: "Visa",
      last4: "4242",
      expiry: "12/25",
    },
    products: [
      {
        id: "3",
        name: "Bluetooth Speaker",
        quantity: 1,
        price: "$89.99",
        image: "/placeholder.svg?height=80&width=80&text=Speaker",
        sku: "BS-003",
      },
    ],
    timeline: [
      {
        status: "Order Placed",
        date: "2024-01-18 2:15 PM",
        completed: true,
        description: "Your order has been received and is being processed",
      },
      {
        status: "Payment Confirmed",
        date: "2024-01-18 2:20 PM",
        completed: true,
        description: "Payment has been successfully processed",
      },
      {
        status: "Processing",
        date: "2024-01-19 10:00 AM",
        completed: true,
        description: "Your items are being prepared for shipment",
      },
      {
        status: "Shipped",
        date: "2024-01-20 11:30 AM",
        completed: true,
        description: "Your order has been shipped and is on its way",
      },
      {
        status: "Out for Delivery",
        date: "Expected: 2024-01-25",
        completed: false,
        description: "Your package will be out for delivery",
      },
      {
        status: "Delivered",
        date: "Expected: 2024-01-25",
        completed: false,
        description: "Package will be delivered",
      },
    ],
  },
};
